# Generated by Django 4.0.3 on 2023-05-12 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents_information',
            name='residents_doorpasswd',
            field=models.IntegerField(verbose_name='입주자현관문비밀번호'),
        ),
        migrations.AlterField(
            model_name='safetyaccident',
            name='safetyaccident_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 5, 37, 44, 475596, tzinfo=utc), verbose_name='안전사고발생날짜'),
        ),
    ]
