# Generated by Django 4.0.3 on 2023-05-16 01:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_residents_information_residents_doorpasswd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyaccident',
            name='safetyaccident_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 1, 36, 7, 667962, tzinfo=utc), verbose_name='안전사고발생날짜'),
        ),
    ]
