# Generated by Django 4.0.3 on 2023-05-17 05:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_safetyaccident_safetyaccident_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginforClient',
        ),
        migrations.AlterField(
            model_name='loginforadministrator',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='session'),
        ),
        migrations.AlterField(
            model_name='safetyaccident',
            name='safetyaccident_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 5, 32, 25, 892704, tzinfo=utc), verbose_name='안전사고발생날짜'),
        ),
    ]
